version: '3.7'

services:
  web:
    build: ./services/web
    #image: web   # tags container SUPPOSEDLY
    command: sh -c  "
        celery -A celery_worker.celery worker --detach &&
        echo ________celery worker is running now________ &&
        python manage.py run -h 0.0.0.0"
        
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

  redis:
    image: redis:latest 
    volumes:
      - redis:/data
    
volumes:
  postgres_data:
  redis: